// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)

import FadeInController from "controllers/fade_in_controller"
application.register("fade-in", FadeInController)

import FiltersController from "controllers/filters_controller"
application.register("filters", FiltersController)

import FlashController from "controllers/flash_controller"
application.register("flash", FlashController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import HillchartController from "controllers/hillchart_controller"
application.register("hillchart", HillchartController)

import ReportDraftController from "controllers/report_draft_controller"
application.register("report-draft", ReportDraftController)

import SortableController from "controllers/sortable_controller"
application.register("sortable", SortableController)

import SortableScopeController from "controllers/sortable_scope_controller"
application.register("sortable-scope", SortableScopeController)

import TeamReportsController from "controllers/team_reports_controller"
application.register("team-reports", TeamReportsController)

import ThemeController from "controllers/theme_controller"
application.register("theme", ThemeController)

import ThemeDarkController from "controllers/theme_dark_controller"
application.register("theme-dark", ThemeDarkController)

import UserSelectController from "controllers/user_select_controller"
application.register("user-select", UserSelectController)
