# Regenerates app/assets/tailwind/icons.css from the Iconify icon classes used
# in the codebase.
#
# We render Iconify CSS icons (e.g. `class="iconify lucide--check size-4"`)
# without the @iconify/tailwind4 plugin / node_modules, by shipping static
# mask rules. This task rescans the views and rebuilds that file, so adding a
# new `lucide--<name>` (or hugeicons/ri) in a template just needs:
#
#   docker compose exec rails bash -lc "bin/rails icons:build"
#
# It fetches SVGs from the public Iconify API (https://iconify.design) at
# build time — pure Ruby, no npm. After running, rebuild Tailwind:
#
#   docker compose exec rails bash -lc "bin/rails tailwindcss:build"

require "net/http"
require "uri"
require "json"

namespace :icons do
  # Icon set prefixes we support. Matches the Nexus template config.
  PREFIXES = %w[lucide hugeicons ri].freeze
  SCAN_DIRS = %w[app/views app/components app/helpers].freeze
  OUTPUT = "app/assets/tailwind/icons.css".freeze
  API = "https://api.iconify.design".freeze

  desc "Rebuild app/assets/tailwind/icons.css from icon classes used in the codebase"
  task :build do
    root = File.expand_path("../..", __dir__)
    used = scan_used_icons(root)
    abort "No icon classes found — nothing to write." if used.empty?

    rules = []
    missing = []
    used.sort.each do |full|
      prefix, name = full.split("--", 2)
      svg = fetch_svg(prefix, name)
      if svg
        rules << %(.#{full} { --svg: url("data:image/svg+xml,#{encode_svg(svg)}"); })
      else
        missing << full
      end
    end

    File.write(File.join(root, OUTPUT), build_css(rules))
    puts "Wrote #{OUTPUT} with #{rules.size} icon(s)."
    warn "WARNING: could not fetch #{missing.size}: #{missing.join(', ')}" if missing.any?
  end

  # --- helpers -------------------------------------------------------------

  def scan_used_icons(root)
    pattern = /(?:#{PREFIXES.join('|')})--[a-z0-9-]+/
    SCAN_DIRS.flat_map do |dir|
      Dir.glob(File.join(root, dir, "**", "*")).select { |f| File.file?(f) }
         .flat_map { |f| File.read(f).scan(pattern) }
    end.uniq
  end

  # Fetch a 24x24 SVG for prefix/name from the Iconify API. Returns nil on 404.
  def fetch_svg(prefix, name)
    uri = URI("#{API}/#{prefix}/#{name}.svg?height=24&width=24")
    res = Net::HTTP.get_response(uri)
    body = res.body.to_s
    return nil unless res.is_a?(Net::HTTPSuccess) && body.start_with?("<svg")
    body
  end

  # Encode an SVG for an inline `data:image/svg+xml,` URL the same way the
  # @iconify/tailwind4 plugin does (single quotes, minimal percent-encoding).
  def encode_svg(svg)
    svg.gsub("%", "%25")
       .gsub('"', "'")
       .gsub("#", "%23")
       .gsub("<", "%3C")
       .gsub(">", "%3E")
       .gsub(/\s+/, " ")
       .strip
  end

  def build_css(rules)
    <<~CSS
      /* Generated by `bin/rails icons:build` — do not edit by hand.
         Static Iconify mask rules so icons render without the
         @iconify/tailwind4 plugin / node_modules. */
      .iconify {
        width: 1em;
        height: 1em;
        -webkit-mask-image: var(--svg);
        mask-image: var(--svg);
        background-color: currentColor;
        display: inline-block;
        -webkit-mask-size: 100% 100%;
        mask-size: 100% 100%;
        -webkit-mask-repeat: no-repeat;
        mask-repeat: no-repeat;
      }

      #{rules.join("\n")}
    CSS
  end
end
