require "rails_helper"

# CI guard for the outbox tradeoff: create/update publishes run inside the
# domain transaction, so an action missing from Pulse::Event::CATALOG fails
# the *host model's save*, not just the notification. Catch that here instead
# of in production.
RSpec.describe "Pulse event catalog coverage" do
  let(:known_actions) { Pulse::Event::CATALOG + Pulse.config.catalog_extensions }

  it "includes every action literal published from app code" do
    published = Dir[Rails.root.join("app/**/*.rb")].flat_map do |file|
      source = File.read(file)
      source.scan(/publish_pulse_event(?:_safely)?\(\s*"([a-z_]+\.[a-z_]+)"/).flatten +
        source.scan(/\baction:\s*"([a-z_]+\.[a-z_]+)"/).flatten
    end.uniq

    expect(published).not_to be_empty
    expect(known_actions).to include(*published)
  end

  it "includes the lifecycle actions generated by publishes_pulse_events for every publishable model" do
    Rails.application.eager_load!
    prefixes = ApplicationRecord.descendants
      .select { |klass| klass.respond_to?(:pulse_event_prefix) && klass.pulse_event_prefix.present? }
      .map(&:pulse_event_prefix).uniq

    expect(prefixes).not_to be_empty
    lifecycle_actions = prefixes.flat_map do |prefix|
      %w[created updated deleted restored].map { |suffix| "#{prefix}.#{suffix}" }
    end
    expect(known_actions).to include(*lifecycle_actions)
  end

  it "has notification copy for every catalog action" do
    Pulse::Event::CATALOG.each do |action|
      expect(I18n.exists?("pulse.events.#{action}"))
        .to be(true), "missing i18n key pulse.events.#{action}"
    end
  end
end
